<?php

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 12/9/2016
 * Time: 2:46 PM
 */

App::uses('ADController', 'Controller');
App::uses('User', 'Model');
App::uses('UsersOvertime', 'Model');


/**
 * class position
 * @property ADController
 * @property Position
 * manage positon staff in company
 */

class OvertimesController extends  ADController {
    public $components = array('Paginator');

    public $paginate = array(
        'limit' => 20,
        'conditions' => array(
            'UsersOvertime.status' => Constants::STATUS_LIVE
        ),

    );

    public function beforeFilter() {
        parent::beforeFilter(); // TODO: Change the autogenerated stub
        $this->loadModel('UsersOvertime');
        $this->layout = 'admin';
    }
    
    public function admin_index() {

        $this->paginate['conditions'] = [
            'UsersOvertime.status' => 0
        ];
        $this->paginate['order'] = ['UsersOvertime.time_in' => 'DESC'];
        $this->Paginator->settings = $this->paginate;
        $data = $this->Paginator->paginate('UsersOvertime');
        $this->set('data', $data);
    }

    public function admin_check() {
    	
        if(!$this->request->data['id']) {
            return $this->_falseJson(Constants::BAD_REQUEST, null, ['message' => 'Data is null']);
        }
        $this->UsersOvertime->validate = [];
        $this->UsersOvertime->id = $this->request->data['id'];
        $result = $this->UsersOvertime->save(['status' => 1]);
        if ($result) {
            return $this->_trueJson(['message' => 'success']);
        }
    }


}
